spring.application.name=fintech-platform

# Database Configuration (Docker PostgreSQL)
spring.datasource.url=jdbc:postgresql://postgres:5432/fintechdb
spring.datasource.username=postgres
spring.datasource.password=Priya666,.
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=mySecretKeyForJWTTokenGenerationPleaseChangeThisInProduction256Bits
jwt.expiration=86400000
jwt.refresh.expiration=604800000

# Redis Configuration
# spring.data.redis.host=redis
# spring.data.redis.port=6379
# spring.data.redis.timeout=60000

# Server Configuration
server.port=8081
server.error.include-message=always
server.error.include-binding-errors=always

# Logging
logging.level.com.fintech=INFO
logging.level.org.springframework.security=WARN

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nexavaultfintechapp@gmail.com
spring.mail.password=zczifpucfxcfsfdm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Application Email
app.mail.from=nexavaultfintechapp@gmail.com
app.name=NexaVault FinTech Platform

# CORS Configuration
cors.allowed.origins=http://localhost:4200,http://localhost,http://localhost:80